spring:
  application:
    name: market-app

  r2dbc:
    url: r2dbc:postgresql://${HOST:localhost}:${PORT:5432}/${POSTGRES_DB:market_db}
    username: ${POSTGRES_USER:dev}
    password: ${POSTGRES_PASSWORD:qwerty}

  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

server:
  port: 8080

logging:
  file:
    path: logs
  level:
    org.springframework.web: info
    root: info
